"""M10 WP-100: the morning brief, composed and pinned to its payload
(Docs/M10_DECOMPOSITION.md §3 C15, §3.1, §7; plan.md §7.3 row 100).

No database: `brief.compose` is handed the dashboard read's own JSON, so every
case here is the payload a phone's brief is actually built from. The five
committed mock fixtures are the real arithmetic of the shipped modules
(`apps/web/src/lib/mock/dashboard`, regenerated by `generate.py`), and the
hand-built cases are the shapes those five do not carry - a chain of one, a
chain of twelve, a single rise, a note long enough to break Meta's rule.

Every number in every line is read back out of the same dict the line was
composed from and compared, never retyped: a figure that drifts from its field
is the one failure this file exists to catch. The forbidden words are checked
by rendering the brief and reading the string, never by grepping the module.

Two fields the brief needs - `total.cost` and `total.costed_sales` - are
WP-101's addition to the wire and are not in the committed fixtures yet, so
`_payload` sets them here from the fixture's own costed rows: the material cost
of the costed rows and their net item sales. `test_the_cost_fields_are_the_sums_of_the_costed_rows`
pins those sums to the figures hand-checked in the decomposition (AED 18,342.39
and AED 56,294.45 for `full`) and to the chain's own contribution, so the
stand-in cannot be quietly wrong.
"""

import json
from decimal import Decimal
from pathlib import Path

import pytest

from faida_api import brief
from faida_api.contribution import _money_words, _pct_words

D = Decimal
MOCK = Path(__file__).resolve().parents[3] / "apps" / "web" / "src" / "lib" / "mock" / "dashboard"
FORBIDDEN = ("food cost", "net profit", "verified")


# --- the payloads -----------------------------------------------------------


def _with_cost_fields(data: dict) -> dict:
    """WP-101's two additive fields, stood in from the payload's own item rows
    until that lane lands: the costed rows' material cost and their net item
    sales. A read with nothing costed carries neither, which is the withheld
    case the brief must say in words."""
    rows = [r for r in data["items"]["all"] if r["contribution"] is not None]
    data["total"]["cost"] = str(sum((D(r["cost"]) for r in rows), D(0))) if rows else None
    data["total"]["costed_sales"] = (
        str(sum((D(r["net_item_sales"]) for r in rows), D(0))) if rows else None
    )
    return data


def _payload(name: str, scope: str = "") -> dict:
    return _with_cost_fields(json.loads((MOCK / f"{name}.json").read_text())[scope])


def _branch(
    branch_id: str,
    name: str,
    *,
    month: str | None,
    contribution_pct: str | None,
    window: tuple[str, str] = ("2026-08-25", "2026-08-31"),
) -> dict:
    return {
        "branch_id": branch_id,
        "branch_name": name,
        "window": {"from": window[0], "to": window[1], "days": 7},
        "net_sales": month,
        "contribution_pct": contribution_pct,
        "costed_share_pct": "90.0",
        "contribution_quality": "reliable_with_limitations",
    }


def _item(item_id: str, name: str, contribution: str) -> dict:
    return {
        "menu_item_id": item_id,
        "menu_item_name": name,
        "contribution": contribution,
        "cost": "1.00",
        "net_item_sales": "10.00",
    }


def _hand(
    *,
    league: list[dict],
    latest: list[tuple[str, str]],
    sentence: str = "Sales loaded to Mon 31 Aug, yesterday.",
    freshness_quality: str = "reliable_with_limitations",
    net_sales: str = "10000.00",
    cost: str | None = "3000.00",
    costed_sales: str | None = "9000.00",
    costed_share_pct: str | None = "90.0",
    contribution_pct: str | None = "66.7",
    contribution_quality: str = "reliable_with_limitations",
    contribution_notes: tuple[str, ...] = (),
    top: list[dict] | None = None,
    bottom: list[dict] | None = None,
    all_items: list[dict] | None = None,
    count: int | None = None,
    moves: list[dict] | None = None,
    period_from: str = "2026-08-04",
) -> dict:
    """A dashboard payload by hand, in the route's own shape: only the keys the
    brief reads, so a case says exactly what it is about."""
    top = top or []
    bottom = bottom or []
    return {
        "period": {"from": period_from, "to": "2026-08-31"},
        "freshness": {"sentence": sentence, "quality": freshness_quality},
        "latest_day": {
            "date": "2026-08-31",
            "net_sales": "4000.00",
            "branches": [
                {"branch_id": bid, "branch_name": bid, "net_sales": value} for bid, value in latest
            ],
        },
        "league": league,
        "total": {
            "net_sales": net_sales,
            "cost": cost,
            "costed_sales": costed_sales,
            "costed_share_pct": costed_share_pct,
            "contribution_pct": contribution_pct,
            "contribution_quality": contribution_quality,
            "contribution_notes": list(contribution_notes),
        },
        "items": {
            "top": top,
            "bottom": bottom,
            "all": all_items if all_items is not None else [*top, *bottom],
            "count": count if count is not None else len({i["menu_item_id"] for i in top + bottom}),
        },
        "price_moves": {"count": len(moves or []), "moves": moves or []},
    }


def _move(name: str, money: str | None, *, direction: str = "up") -> dict:
    return {
        "ingredient_name": name,
        "direction": direction,
        "money_at_stake": money,
        "sentence": f"{name} is up AED 1.00 per kg since 21 Aug.",
    }


# --- the five lines, against the committed fixtures --------------------------


def test_the_cost_fields_are_the_sums_of_the_costed_rows():
    """The stand-in for WP-101's two fields is the decomposition's own
    hand-check: 18,342.39 of materials against 56,294.45 of costed sales, whose
    difference is the chain's contribution to the fils."""
    full = _payload("full")
    assert full["total"]["cost"] == "18342.39"
    assert full["total"]["costed_sales"] == "56294.45"
    assert D(full["total"]["costed_sales"]) - D(full["total"]["cost"]) == D(
        full["total"]["contribution"]
    )


def test_the_full_fixture_says_every_figure_the_payload_gives():
    month = _payload("full")
    made = brief.compose(month, month)

    assert not made.quiet
    assert made.day == month["freshness"]["sentence"]
    assert made.latest_day == (
        f"{_money_words(D(month['latest_day']['net_sales']), 'AED')} on Mon 31 Aug"
    )
    assert made.month_to_date == (
        f"{_money_words(D(month['total']['net_sales']), 'AED')} (25-31 Aug loaded)"
    )
    assert made.materials_used == (
        f"{_money_words(D(month['total']['cost']), 'AED')} at the latest prices (estimated)"
    )
    share = D(100) - D(month["total"]["contribution_pct"])
    assert made.materials_share == (
        f"{share}% of the {_money_words(D(month['total']['costed_sales']), 'AED')} costed "
        f"({_pct_words(D(month['total']['costed_share_pct']))} of sales) (estimated)"
    )
    # The shape the founder was shown, to the character.
    assert made.latest_day == "AED 9,493 on Mon 31 Aug"
    assert made.month_to_date == "AED 67,471 (25-31 Aug loaded)"
    assert made.materials_share.startswith("32.6% of the AED 56,294 costed (84% of sales)")


def test_the_materials_share_is_a_hundred_less_the_share_kept():
    for name in ("full", "partial", "quiet"):
        month = _payload(name)
        made = brief.compose(month, month)
        kept = D(month["total"]["contribution_pct"])
        assert made.materials_share.startswith(f"{D(100) - kept}%")
        assert made.kpis[3].value == f"{D(100) - kept}%"


def test_the_four_tiles_carry_the_same_figures_as_the_four_lines():
    month = _payload("full")
    made = brief.compose(month, month)
    latest, mtd, used, share = made.kpis

    assert [k.label for k in made.kpis] == [
        "Latest day",
        "Month to date",
        "Materials used",
        "Materials share",
    ]
    assert latest.value == _money_words(D(month["latest_day"]["net_sales"]), "AED")
    assert latest.sub == "Mon 31 Aug"
    assert mtd.value == _money_words(D(month["total"]["net_sales"]), "AED")
    assert mtd.sub == "25-31 Aug loaded"
    assert used.value == _money_words(D(month["total"]["cost"]), "AED")
    assert used.sub == "at the latest prices (estimated)"
    assert share.value == f"{D(100) - D(month['total']['contribution_pct'])}%"
    assert share.sub == (
        f"of {_money_words(D(month['total']['costed_sales']), 'AED')} costed · "
        f"{_pct_words(D(month['total']['costed_share_pct']))} of sales (estimated)"
    )
    # Each line is built out of its tile, so the two cannot drift.
    assert made.latest_day == f"{latest.value} on {latest.sub}"
    assert made.month_to_date == f"{mtd.value} ({mtd.sub})"
    assert made.materials_used == f"{used.value} {used.sub}"


def test_the_stale_read_says_so_after_the_sentence_and_never_says_yesterday():
    month = _payload("partial")
    made = brief.compose(month, month)

    assert month["freshness"]["quality"] == "estimated"
    assert made.day == month["freshness"]["sentence"] + brief.STALE_CLAUSE
    assert "yesterday" not in brief.render(made)
    assert "12 days ago" in made.day


def test_the_word_yesterday_is_the_wires_and_only_the_wires():
    fresh = _hand(
        league=[_branch("b1", "Al Quoz", month="10000.00", contribution_pct="66.7")],
        latest=[("b1", "4000.00")],
        sentence="Sales loaded to Mon 31 Aug, yesterday.",
    )
    assert "yesterday" in brief.render(brief.compose(fresh, fresh))


def test_an_incomplete_read_carries_its_first_note_on_the_materials_lines():
    month = _payload("partial")
    made = brief.compose(month, month)
    note = month["total"]["contribution_notes"][0]

    assert month["total"]["contribution_quality"] == "incomplete"
    assert made.materials_used.endswith(f" (incomplete: {note})")
    assert made.materials_share.endswith(f" (incomplete: {note})")
    assert made.kpis[2].sub.endswith(f" (incomplete: {note})")


def test_the_month_line_says_when_branches_loaded_different_days():
    month = _payload("partial")
    made = brief.compose(month, month)
    loaded = [r for r in month["league"] if r["net_sales"] is not None]

    assert {r["window"]["from"] for r in loaded} == {"2026-08-25"}
    assert any(r["window"]["from"] != "2026-08-25" for r in month["league"])
    assert made.month_to_date == (
        f"{_money_words(D(month['total']['net_sales']), 'AED')} "
        "(25-31 Aug loaded; some branches fewer)"
    )


def test_a_read_with_nothing_costed_withholds_both_materials_lines():
    month = _payload("nomenu")
    made = brief.compose(month, month)
    note = month["total"]["contribution_notes"][0]

    assert month["total"]["cost"] is None
    assert made.materials_used == f"not available ({note})"
    assert made.materials_share == f"not available ({note})"
    assert made.kpis[2] == brief.Kpi("Materials used", "not available", note)
    assert made.kpis[3] == brief.Kpi("Materials share", "not available", note)
    assert "0%" not in made.materials_share.replace(note, "")
    assert all(row.materials_share_words == brief.HOLE for row in made.rows)


def test_a_withheld_figure_with_no_note_still_says_why():
    month = _hand(
        league=[_branch("b1", "Al Quoz", month="10000.00", contribution_pct=None)],
        latest=[("b1", "4000.00")],
        cost=None,
        costed_sales=None,
        costed_share_pct=None,
        contribution_pct=None,
    )
    made = brief.compose(month, month)
    assert made.materials_used == f"not available ({brief.NO_NOTE})"
    assert made.materials_share == f"not available ({brief.NO_NOTE})"


# --- the branch table --------------------------------------------------------


def test_every_branch_row_carries_the_leagues_own_figures_in_the_leagues_order():
    month = _payload("full")
    made = brief.compose(month, month)
    on_day = {b["branch_id"]: b for b in month["latest_day"]["branches"]}

    assert [row.name for row in made.rows] == [r["branch_name"] for r in month["league"]]
    for row, source in zip(made.rows, month["league"], strict=True):
        assert row.month == D(source["net_sales"]).quantize(D(1))
        assert row.latest_day == D(on_day[source["branch_id"]]["net_sales"]).quantize(D(1))
        assert row.materials_share == str(D(100) - D(source["contribution_pct"]))
        assert row.materials_share_words == f"{row.materials_share}%"
    assert made.rows[-1].name == "Al Quoz"
    assert made.rows[-1].latest_day_words == "4,385"
    assert made.rows[-1].month_words == "30,719"
    assert made.rows[-1].materials_share_words == "30.1%"


def test_a_branch_with_no_sales_on_the_latest_day_shows_a_hole_and_never_a_nought():
    month = _payload("partial")
    made = brief.compose(month, month)
    deira = next(row for row in made.rows if row.name == "Deira")
    deira_id = next(r["branch_id"] for r in month["league"] if r["branch_name"] == "Deira")

    assert deira_id not in {b["branch_id"] for b in month["latest_day"]["branches"]}
    assert next(r for r in month["league"] if r["branch_id"] == deira_id)["net_sales"] is None
    assert deira.latest_day is None and deira.latest_day_words == brief.HOLE
    assert deira.month is None and deira.month_words == brief.HOLE
    assert deira.materials_share is None and deira.materials_share_words == brief.HOLE


def test_the_branch_name_is_the_short_one():
    month = _hand(
        league=[_branch("b1", "Rolla Branch", month="10000.00", contribution_pct="66.7")],
        latest=[("b1", "4000.00")],
    )
    assert brief.compose(month, month).rows[0].name == "Rolla"


def test_a_chain_of_one_branch_has_one_row_saying_the_chains_own_figures():
    month = _hand(
        league=[_branch("b1", "Al Quoz", month="10000.00", contribution_pct="66.7")],
        latest=[("b1", "4000.00")],
        net_sales="10000.00",
    )
    made = brief.compose(month, month)

    assert len(made.rows) == 1
    assert made.rows[0].month == D(10000)
    assert made.month_to_date == "AED 10,000 (25-31 Aug loaded)"
    assert made.rows[0].materials_share == "33.3"


# --- the two item lists ------------------------------------------------------


def test_the_two_lists_are_the_dashboards_own_rows_worst_first_among_the_worst():
    month = _payload("full")
    made = brief.compose(month, month)

    assert [line.name for line in made.earning_most] == [
        r["menu_item_name"] for r in month["items"]["top"][:3]
    ]
    assert [line.name for line in made.earning_least] == [
        r["menu_item_name"] for r in reversed(month["items"]["bottom"][-3:])
    ]
    for line, source in zip(made.earning_most, month["items"]["top"][:3], strict=True):
        assert line.money == D(source["contribution"])
        assert line.money_words == _money_words(line.money, "AED")
    assert [line.money_words for line in made.earning_most] == [
        "AED 11,177",
        "AED 7,821",
        "AED 4,862",
    ]
    # The founder's sample line, in the founder's order.
    assert [line.money_words for line in made.earning_least] == [
        "AED -107",
        "AED 741",
        "AED 1,283",
    ]


def test_a_loss_keeps_its_sign():
    month = _payload("full")
    made = brief.compose(month, month)
    worst = made.earning_least[0]
    assert worst.money < 0
    assert worst.money_words.startswith("AED -")


def test_the_items_that_could_not_be_costed_are_counted():
    month = _payload("full")
    made = brief.compose(month, month)
    assert made.uncosted == len(month["items"]["all"]) - month["items"]["count"]
    assert made.uncosted == 2


def test_with_five_or_fewer_costed_items_the_worst_list_is_what_is_left():
    """`items.bottom` is empty until six items are costed, so the worst come
    off the end of the top list - and an item already named among the best is
    never named again among the worst."""
    month = _payload("quiet")
    made = brief.compose(month, month)

    assert month["items"]["bottom"] == []
    assert month["items"]["count"] == 4
    assert [line.name for line in made.earning_most] == [
        r["menu_item_name"] for r in month["items"]["top"][:3]
    ]
    fourth = month["items"]["top"][3]["menu_item_name"]
    assert [line.name for line in made.earning_least] == [fourth]
    assert not {line.name for line in made.earning_most} & {
        line.name for line in made.earning_least
    }


def test_with_exactly_five_costed_items_the_worst_two_are_the_two_the_best_left():
    top = [_item(f"i{n}", f"Item {n}", f"{1000 - n * 100}.00") for n in range(1, 6)]
    month = _hand(
        league=[_branch("b1", "Al Quoz", month="10000.00", contribution_pct="66.7")],
        latest=[("b1", "4000.00")],
        top=top,
        all_items=top,
        count=5,
    )
    made = brief.compose(month, month)

    assert [line.name for line in made.earning_most] == ["Item 1", "Item 2", "Item 3"]
    assert [line.name for line in made.earning_least] == ["Item 5", "Item 4"]
    assert made.earning_least[0].money == D("500.00")
    assert made.uncosted == 0


def test_a_menu_with_nothing_costed_names_no_item():
    month = _payload("nomenu")
    made = brief.compose(month, month)
    assert made.earning_most == () and made.earning_least == ()


# --- the price spikes --------------------------------------------------------


def test_the_spikes_are_the_windows_rises_ranked_by_money():
    window = _payload("full")
    made = brief.compose(window, window)
    rises = [m for m in window["price_moves"]["moves"] if m["direction"] == "up"]

    assert len(made.spikes) == 3
    assert [s.sentence for s in made.spikes] == [m["sentence"] for m in rises]
    assert made.spikes[0].money_clause == (
        f"{_money_words(D(rises[0]['money_at_stake']), 'AED')} at stake on sales since."
    )
    assert made.spikes[0].money_clause == "AED 109 at stake on sales since."
    assert made.no_spikes is None
    assert all(m["direction"] == "up" for m in rises)
    assert "down" in {m["direction"] for m in window["price_moves"]["moves"]}


def test_a_rise_nothing_was_sold_after_says_so_and_never_prints_a_nought():
    window = _payload("full")
    made = brief.compose(window, window)
    chicken = next(s for s in made.spikes if s.sentence.startswith("Chicken"))
    assert chicken.money_clause == "Nothing sold since."
    assert "AED 0" not in chicken.money_clause


def test_fewer_than_three_rises_is_the_rises_there_are():
    window = _hand(
        league=[_branch("b1", "Al Quoz", month="10000.00", contribution_pct="66.7")],
        latest=[("b1", "4000.00")],
        moves=[_move("Milk Powder", "40.00"), _move("Cream", "-9.00", direction="down")],
    )
    made = brief.compose(window, window)
    assert len(made.spikes) == 1
    assert made.spikes[0].sentence == window["price_moves"]["moves"][0]["sentence"]
    assert made.no_spikes is None


def test_the_spikes_are_ranked_by_the_money_at_stake():
    window = _hand(
        league=[_branch("b1", "Al Quoz", month="10000.00", contribution_pct="66.7")],
        latest=[("b1", "4000.00")],
        moves=[
            _move("Small", "3.00"),
            _move("Biggest", "900.00"),
            _move("Middle", "50.00"),
            _move("Tiny", "0.00"),
        ],
    )
    made = brief.compose(window, window)
    assert [s.sentence.split()[0] for s in made.spikes] == ["Biggest", "Middle", "Small"]


def test_no_move_at_all_says_so_at_the_gate_and_from_the_windows_own_start():
    window = _payload("quiet")
    made = brief.compose(window, window)
    assert window["price_moves"]["count"] == 0
    assert made.spikes == ()
    assert made.no_spikes == "none of 5% or more since 4 Aug."
    assert window["period"]["from"] == "2026-08-04"


def test_the_month_figures_come_from_the_month_read_and_the_spikes_from_the_window():
    month = _payload("full")
    window = _payload("quiet")
    made = brief.compose(month, window)

    assert made.month_to_date == (
        f"{_money_words(D(month['total']['net_sales']), 'AED')} (25-31 Aug loaded)"
    )
    assert "67,471" in made.month_to_date and "29,126" not in made.month_to_date
    assert made.spikes == ()
    assert made.no_spikes == "none of 5% or more since 4 Aug."

    swapped = brief.compose(window, month)
    assert "29,126" in swapped.month_to_date
    assert len(swapped.spikes) == 3


# --- the quiet morning -------------------------------------------------------


def test_a_read_with_nothing_loaded_is_quiet_and_has_no_lines():
    month = _payload("empty")
    made = brief.compose(month, month)

    assert month["freshness"]["sentence"] is None and month["latest_day"] is None
    assert made.quiet
    assert (made.day, made.latest_day, made.month_to_date) == ("", "", "")
    assert (made.materials_used, made.materials_share) == ("", "")
    assert made.parameters == () and made.kpis == () and made.rows == ()
    assert made.earning_most == () and made.earning_least == () and made.spikes == ()
    with pytest.raises(ValueError, match="nothing to render"):
        brief.render(made)


def test_a_read_whose_newest_day_is_outside_the_period_is_quiet_too():
    month = _hand(
        league=[_branch("b1", "Al Quoz", month="10000.00", contribution_pct="66.7")],
        latest=[("b1", "4000.00")],
    )
    month["latest_day"] = None
    assert brief.compose(month, month).quiet


# --- the parameters and the body ---------------------------------------------


def test_the_five_parameters_are_the_five_lines_in_the_templates_order():
    month = _payload("full")
    made = brief.compose(month, month)
    assert made.parameters == (
        made.day,
        made.latest_day,
        made.month_to_date,
        made.materials_used,
        made.materials_share,
    )
    assert len(made.parameters) == brief.PARAMETER_COUNT


def test_every_parameter_obeys_metas_rules_on_every_fixture():
    for name in ("full", "partial", "quiet", "nomenu"):
        month = _payload(name)
        made = brief.compose(month, month)
        for value in made.parameters:
            assert "\n" not in value and "\r" not in value and "\t" not in value
            assert "    " not in value
            assert 0 < len(value) <= brief.PARAMETER_MAX_CHARS


def test_a_line_over_the_cap_is_a_named_failure_and_never_a_truncated_message():
    month = _hand(
        league=[_branch("b1", "Al Quoz", month="10000.00", contribution_pct="66.7")],
        latest=[("b1", "4000.00")],
        contribution_quality="incomplete",
        contribution_notes=("a note about the read that runs on and on " * 5,),
    )
    with pytest.raises(ValueError, match="materials used"):
        brief.compose(month, month)


def test_a_line_carrying_a_line_break_is_a_named_failure():
    month = _hand(
        league=[_branch("b1", "Al Quoz", month="10000.00", contribution_pct="66.7")],
        latest=[("b1", "4000.00")],
        sentence="Sales loaded to Mon 31 Aug,\nyesterday.",
    )
    with pytest.raises(ValueError, match="the day line carries a line break"):
        brief.compose(month, month)


def test_the_body_carries_exactly_the_parameters_the_filler_fills():
    month = _payload("full")
    made = brief.compose(month, month)
    body = brief.render(made)

    assert brief.TEMPLATE_BODY.count("{{") == brief.PARAMETER_COUNT
    assert "{{" not in body
    for value in made.parameters:
        assert value in body
    assert body.startswith("*Faida morning brief*\n")
    assert body.endswith("Every figure opens to its source on the dashboard.")
    assert brief.TEMPLATE_NAME == "faida_daily_brief"
    assert brief.TEMPLATE_LANGUAGE == "en"


def test_a_chain_of_twelve_branches_still_renders_inside_metas_cap():
    league = [
        _branch(f"b{n}", f"Branch Number {n}", month=f"{n}000.00", contribution_pct="66.7")
        for n in range(1, 13)
    ]
    month = _hand(
        league=league,
        latest=[(f"b{n}", f"{n}00.00") for n in range(1, 13)],
        net_sales="78000.00",
    )
    made = brief.compose(month, month)

    assert len(made.rows) == 12
    assert len(brief.render(made)) < brief.BODY_MAX_CHARS
    assert len(brief.render(made)) == len(brief.render(brief.compose(_shrink(month), month)))


def _shrink(month: dict) -> dict:
    """The same chain with one branch: the five lines do not grow with the
    branch count by design, and the twelve-branch test proves it by measuring
    both renderings."""
    one = json.loads(json.dumps(month))
    one["league"] = one["league"][:1]
    one["latest_day"]["branches"] = one["latest_day"]["branches"][:1]
    return one


def test_the_card_footer_is_the_one_qualification_the_card_carries():
    month = _payload("full")
    made = brief.compose(month, month)
    assert made.card_footer == brief.CARD_FOOTER
    assert "costed" in made.card_footer
    assert made.card_footer.endswith("Every figure opens to its source on the dashboard.")


# --- the words that must never appear ----------------------------------------


def test_no_rendering_of_any_fixture_carries_a_forbidden_phrase():
    for name in ("full", "partial", "quiet", "nomenu"):
        month = _payload(name)
        made = brief.compose(month, month)
        printed = " ".join(
            [
                brief.render(made),
                made.card_footer,
                made.no_spikes or "",
                *[f"{k.label} {k.value} {k.sub}" for k in made.kpis],
                *[f"{r.name} {r.latest_day_words} {r.month_words}" for r in made.rows],
                *[f"{i.name} {i.money_words}" for i in (*made.earning_most, *made.earning_least)],
                *[f"{s.sentence} {s.money_clause}" for s in made.spikes],
            ]
        ).lower()
        for phrase in FORBIDDEN:
            assert phrase not in printed, f"{name} says {phrase!r}"
        assert "materials share" in brief.TEMPLATE_BODY.lower()
