"""M13 WP-131: the staff incentive, pure - the calendar rules, every figure
and every sentence of a branch's statement, and the wire shapes the screen
and the scoreboard read (plan.md §8 M13, D1 to D18; `CONTEXT.md` for the
words; `Docs/adr/0001` for what is scored on; issue #6 for the arithmetic).

The vocabulary is the glossary's: a **scheme month** is a calendar month,
frozen when created; a **push week** is Monday to Sunday clipped to it; a
**push list** is the push items of one week, each a menu item with a rate
per portion above target and a portion **target** per branch; the **pool** is
what a branch's team has earned for the month, split by the **role shares**
snapshotted when the month was created; the **statement** is the month's
scores and pool as read from the loaded sales days, provisional until every
day is loaded and final once the owner approves it; the staff-facing word is
**bonus**, and never profit share or commission.

Pure by design, in `signals.py`'s and `usage.py`'s shape: no clock, no
database, no HTTP. The read hands it the scheme month as the rows say it,
the branch's loaded days, the till's item days with their menu item read
through the mapping, and the approval if there is one; it hands back figures
and words. That is what makes every rule testable without a database, and
what lets the screen's fixtures be generated by this module rather than
copied from it (the dashboard's `generate.py` rule).

The arithmetic, here and nowhere else (D8, D9, D10):

- portions for a push item in a push week for a branch are the net signed
  quantity of every sales line whose till item maps to that menu item within
  the week's dates, rounded once per item - a refunded plate is not a sold
  plate (D9, the opposite of M12's P9 for a stated reason);
- a push item whose menu item is archived or whose till items are all
  unmapped is a hole: portions None, named in the notes, contributing
  nothing (D7) - never a zero, which would read as a team that sold none;
- net sales for the month are the sum of the loaded days' net sales;
- pool = Σ max(0, portions − target) × rate + max(0, net sales − net target)
  × percentage, then min(cap) where a cap is set; whole dirhams rounded half
  up as the headline, exact to the fil beneath;
- the split is pool × each role share to the fil, the remainder to the sales
  share, so the three sum to the pool;
- a branch with nothing loaded in the month has no pool - None, never a
  zero pool presented as earned;
- the statement says "provisional, N of M days loaded" until N = M, "final"
  once approved, and carries "the till now says otherwise" beside the
  recomputed figures when a day was replaced after approval (D12).

Money words are `contribution._money_words` (whole dirhams) and
`contribution._price_words` (fils, for a rate and what a plate keeps),
portions `signals._portions_words`, dates `ratio.window_words` - imported and
called, never copied, so a rounding rule can only ever change in one place.
`BANNED_WORDS` is checked by a test that calls this module: no composed
sentence ever says profit, profit share, commission, verified or food cost.
"""

import calendar
import datetime
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from decimal import ROUND_HALF_UP, Decimal

from .contribution import _money_words, _price_words
from .ratio import FILS, Window, window_words
from .signals import _portions_words

#: Words no composed sentence may carry (ADR 0001; the glossary's refused
#: words). "profit" covers "profit share" and "net profit".
BANNED_WORDS = ("profit", "commission", "verified", "food cost")

#: The category a menu item with none is grouped under on the screen (D6).
OTHER_CATEGORY = "Other"

#: One to three push items per category, shown as guidance and never
#: enforced (D6): the words the screen prints beside a category.
PUSH_GUIDANCE_WORDS = "one to three per category, as a guide"

PROVISIONAL = "provisional"
FINAL = "final"
TILL_NOW_SAYS_OTHERWISE = "the till now says otherwise"

#: What a push week the owner left empty says (D4, D5).
NO_PUSH_LIST = "no push list"

#: What the pool says when no day of the month is loaded for the branch.
NO_POOL_WORDS = "nothing loaded yet"

#: The staff-facing word (CONTEXT.md).
BONUS = "bonus"

_WHOLE = Decimal("1")
_PORTION = Decimal("0.001")
_PCT = Decimal("0.01")
_HUNDRED = Decimal("100")


# --- the calendar ---------------------------------------------------------------


def month_start(day: datetime.date) -> datetime.date:
    return day.replace(day=1)


def month_end(month: datetime.date) -> datetime.date:
    first = month_start(month)
    return first.replace(day=calendar.monthrange(first.year, first.month)[1])


def days_in_month(month: datetime.date) -> int:
    first = month_start(month)
    return calendar.monthrange(first.year, first.month)[1]


def month_words(month: datetime.date) -> str:
    """ "September 2026" - the scheme month as the owner names it."""
    return f"{month.strftime('%B')} {month.year}"


def month_key(month: datetime.date) -> str:
    """ "2026-09" - the month on the wire and in a URL."""
    return f"{month.year:04d}-{month.month:02d}"


def parse_month_key(key: str) -> datetime.date | None:
    """ "2026-09" to its first day, or None for anything else."""
    try:
        year, month = key.split("-")
        return datetime.date(int(year), int(month), 1)
    except (ValueError, AttributeError):
        return None


def push_weeks(month: datetime.date) -> tuple[Window, ...]:
    """Monday to Sunday, clipped to the month (D5): the first and last week
    may be short, and no statement ever waits for another month's days. A
    month starting on a Wednesday gets a first week of five days; a 31-day
    month starting on a Monday gets five weeks."""
    first, last = month_start(month), month_end(month)
    weeks = []
    cursor = first
    while cursor <= last:
        sunday = cursor + datetime.timedelta(days=6 - cursor.weekday())
        end = min(sunday, last)
        weeks.append(Window(cursor, end))
        cursor = end + datetime.timedelta(days=1)
    return tuple(weeks)


def week_started(window: Window, today: datetime.date) -> bool:
    """A week whose start date is today or earlier is under way and frozen
    (D5); one starting tomorrow or later may still be re-aimed."""
    return window.start <= today


def week_words(window: Window) -> str:
    """ "7-13 Sep", or "28 Sep-4 Oct" across a month end."""
    return window_words(window)


# --- validation the doors share ---------------------------------------------------


def shares_problem(
    manager: Decimal | None, supervisor: Decimal | None, sales: Decimal | None
) -> str | None:
    """The refusal sentence for a set of role shares, or None when they are
    three percentages summing to one hundred (D2).

    Two decimals at most, because that is what a share is stored as
    (`numeric(5,2)`): a third decimal would be rounded away on the way in, and
    three shares that summed to a hundred before the rounding need not sum to
    a hundred after it - which the table's own check would then refuse, in
    SQL, long past the door that should have said so in words.
    """
    for name, value in (("manager", manager), ("supervisor", supervisor), ("sales team", sales)):
        if value is None:
            return f"the {name} share is missing: three percentages summing to 100 are needed"
        if value < 0:
            return f"the {name} share cannot be negative"
        if value.as_tuple().exponent < -2:
            return (
                f"the {name} share is written to more decimals than a share is kept to: "
                "two at most, like 33.33"
            )
    if manager + supervisor + sales != _HUNDRED:
        return (
            f"the three shares sum to {_pct_plain(manager + supervisor + sales)}%, not 100%: "
            "the manager, the supervisor and the sales team must share the whole pool"
        )
    return None


def targets_problem(
    net_sales_target: Decimal | None, above_target_pct: Decimal | None, cap: Decimal | None
) -> str | None:
    """The refusal sentence for one branch's targets, or None. The branch is
    named by `branch_targets_problem`, which is the only caller: these say
    what is wrong with a figure, never which box it came from."""
    if net_sales_target is None:
        return "a net sales target is needed"
    if net_sales_target < 0:
        return "a net sales target cannot be negative"
    if above_target_pct is None:
        return "the percentage of net sales above target is needed"
    if above_target_pct < 0 or above_target_pct > _HUNDRED:
        return "the percentage of net sales above target must be between 0 and 100"
    if cap is not None and cap < 0:
        return "a cap cannot be negative; leave it blank for no cap"
    return None


#: The one refusal when no shares have been set yet: a scheme month is
#: created *with* the shares in force, so there is nothing to snapshot (D2,
#: D4). Worded here because the door that refuses it and the screen that
#: prevents it must say the same thing.
SHARES_NOT_SET = (
    "the role shares are not set: a scheme month is created with the shares in force that day, "
    "so set the three shares first"
)


def month_taken_sentence(month: datetime.date) -> str:
    """Why a second scheme month for the same calendar month is refused (D4):
    the first one was frozen when it was created, and a second would be a
    second set of rules for one month."""
    return (
        f"{month_words(month)} already has a scheme month: it was frozen when it was created, "
        "so its targets cannot be set a second time"
    )


@dataclass(frozen=True)
class TypedTarget:
    """What the owner typed into one branch's three boxes on the create form,
    before it is known to be a target: any of the three may be missing, and
    the cap is blank for no cap. `BranchTargets` is the same figures once
    they are a target - stored, frozen and scored on."""

    branch_id: str
    net_sales_target: Decimal | None
    above_target_pct: Decimal | None
    cap: Decimal | None


def branch_targets_problem(
    branch_names: Mapping[str, str], targets: Sequence[TypedTarget]
) -> str | None:
    """The refusal sentence for a whole month's branch targets, or None (D3).

    Every branch of the chain gets exactly one target and no branch outside it
    gets any, because a scheme month scores every branch and a branch the
    owner did not type a figure for would be scored against nothing. Each
    target is then checked by `targets_problem` and named by the branch whose
    box it came from, so an owner looking at three boxes is told which one.
    """
    seen: list[str] = []
    for target in targets:
        name = branch_names.get(target.branch_id)
        if name is None:
            return "a target was sent for a branch that is not in this chain"
        if target.branch_id in seen:
            return f"{name} was sent two targets; every branch gets one"
        seen.append(target.branch_id)
        problem = targets_problem(target.net_sales_target, target.above_target_pct, target.cap)
        if problem is not None:
            return f"{name}: {problem}"
    missing = [name for branch_id, name in branch_names.items() if branch_id not in seen]
    if missing:
        return (
            f"{_list_words(missing)} {'has' if len(missing) == 1 else 'have'} no target: "
            "every branch of the chain needs one for the month"
        )
    return None


def _list_words(names: Sequence[str]) -> str:
    """ "Deira", "Deira and Karama", "Deira, Karama and Al Quoz"."""
    if len(names) == 1:
        return names[0]
    return f"{', '.join(names[:-1])} and {names[-1]}"


def frozen_week_sentence(window: Window, today: datetime.date) -> str | None:
    """Why a push list cannot be set on this week, or None when it can (D5)."""
    if not week_started(window, today):
        return None
    if window.end < today:
        return f"the week of {week_words(window)} has ended and is frozen"
    return f"the week of {week_words(window)} has started and is frozen"


def push_item_problem(name: str, *, archived: bool, mapped: bool) -> str | None:
    """Why a menu item cannot be a push item, or None (D7)."""
    if archived:
        return f"{name} is archived from the menu and cannot be pushed"
    if not mapped:
        return (
            f"{name} has no till name mapped to it, so it could only ever score zero; "
            "map a till name to it on the Sales screen first"
        )
    return None


def hole_sentence(name: str, *, archived: bool, mapped: bool) -> str | None:
    """Why a push item on a list cannot be counted now, or None (D7): the
    mapping was removed or the dish archived after the list was set."""
    if archived:
        return f"{name} cannot be counted: it was archived from the menu"
    if not mapped:
        return f"{name} cannot be counted: no till name is mapped to it"
    return None


# --- the inputs, as the rows say them --------------------------------------------


@dataclass(frozen=True)
class Shares:
    manager_pct: Decimal
    supervisor_pct: Decimal
    sales_pct: Decimal


@dataclass(frozen=True)
class BranchTargets:
    branch_id: str
    net_sales_target: Decimal
    above_target_pct: Decimal
    cap: Decimal | None


@dataclass(frozen=True)
class PushItem:
    push_item_id: str
    menu_item_id: str
    name: str
    category: str | None
    rate_per_portion: Decimal
    archived: bool
    mapped: bool
    #: Portion target per branch id. A branch with no target scores nothing
    #: on this item.
    targets: Mapping[str, Decimal]


@dataclass(frozen=True)
class PushWeek:
    push_week_id: str
    window: Window
    items: tuple[PushItem, ...]


@dataclass(frozen=True)
class SchemeMonth:
    scheme_month_id: str
    month: datetime.date
    shares: Shares
    targets: Mapping[str, BranchTargets]
    weeks: tuple[PushWeek, ...]


@dataclass(frozen=True)
class LoadedDay:
    branch_id: str
    business_date: datetime.date
    net_sales: Decimal


@dataclass(frozen=True)
class ItemDay:
    """What a till item sold on one branch-day, read through its mapping:
    `qty_net` is the net signed quantity (sold less refunded, D9) and
    `no_qty_lines` the lines that printed no quantity and cannot be counted."""

    branch_id: str
    business_date: datetime.date
    menu_item_id: str | None
    qty_net: Decimal
    no_qty_lines: int = 0


@dataclass(frozen=True)
class Approval:
    approved_at: datetime.datetime
    actor: str
    reason: str
    #: `figures_json` of the statement as approved.
    figures: dict


# --- the figures ----------------------------------------------------------------


@dataclass(frozen=True)
class ItemScore:
    push_item_id: str
    menu_item_id: str
    name: str
    category: str | None
    rate_per_portion: Decimal
    portion_target: Decimal
    #: None is a hole, never a nought.
    portions: Decimal | None
    portions_above: Decimal
    earned: Decimal
    hole: str | None
    no_qty_lines: int
    words: str


@dataclass(frozen=True)
class WeekScore:
    push_week_id: str
    window: Window
    items: tuple[ItemScore, ...]
    earned: Decimal
    empty: bool
    words: str


@dataclass(frozen=True)
class Split:
    shares: Shares
    manager: Decimal
    supervisor: Decimal
    sales: Decimal


@dataclass(frozen=True)
class Figures:
    """Everything derived for one branch and one scheme month, from the loaded
    days and nothing else. The snapshot an approval stores is `figures_json`
    of this."""

    days_loaded: int
    days_in_month: int
    net_sales: Decimal
    net_sales_target: Decimal
    net_above: Decimal
    above_target_pct: Decimal
    net_earned: Decimal
    weeks: tuple[WeekScore, ...]
    items_earned: Decimal
    pool_before_cap: Decimal
    cap: Decimal | None
    capped: bool
    #: None when no day of the month is loaded: there is no pool to speak of.
    pool: Decimal | None
    pool_rounded: Decimal | None
    split: Split | None
    net_words: str
    pool_words: str


@dataclass(frozen=True)
class Statement:
    branch_id: str
    month: datetime.date
    newest_loaded: datetime.date | None
    status: str
    status_words: str
    #: The approved figures once approved, the live ones until then.
    figures: Figures
    approval: Approval | None
    till_now_says_otherwise: bool
    #: The live figures beside an approved statement they no longer match.
    recomputed: Figures | None
    notes: tuple[str, ...]


# --- words ----------------------------------------------------------------------


def _pct_plain(value: Decimal) -> str:
    """ "10" for 10.00, "12.5" for 12.50."""
    normalized = value.normalize()
    if normalized == normalized.to_integral_value():
        return str(int(normalized))
    return f"{normalized:f}"


def _fils(amount: Decimal) -> Decimal:
    return amount.quantize(FILS, rounding=ROUND_HALF_UP)


def _whole(amount: Decimal) -> Decimal:
    return amount.quantize(_WHOLE, rounding=ROUND_HALF_UP)


def kept_words(margin: Decimal | None, currency: str) -> str:
    """What a plate keeps after ingredients, fils-precise, beside the rate
    box - or the honest word for a dish that is not costed (D7, D8)."""
    if margin is None:
        return "not costed"
    return f"keeps {_price_words(margin, currency)} per plate"


def previous_month_words(net_sales: Decimal | None, currency: str) -> str:
    """Last month's net sales beside the target box, as advice and never as
    the baseline (D3)."""
    if net_sales is None:
        return "no sales loaded last month"
    return f"{_money_words(net_sales, currency)} last month"


def target_words(portions: Decimal, target: Decimal) -> str:
    return f"{_portions_words(portions)} of {_portions_words(target)} portions"


def status_words(status: str, days_loaded: int, days_in_month: int, *, differs: bool) -> str:
    if status == FINAL:
        return f"{FINAL}; {TILL_NOW_SAYS_OTHERWISE}" if differs else FINAL
    return f"{PROVISIONAL}, {days_loaded} of {days_in_month} days loaded"


# --- the arithmetic -------------------------------------------------------------


def _portions_for(
    item: PushItem, window: Window, branch_id: str, days: Iterable[ItemDay]
) -> tuple[Decimal, int]:
    total = Decimal(0)
    uncounted = 0
    for day in days:
        if day.branch_id != branch_id or day.menu_item_id != item.menu_item_id:
            continue
        if not (window.start <= day.business_date <= window.end):
            continue
        total += day.qty_net
        uncounted += day.no_qty_lines
    return total.quantize(_PORTION, rounding=ROUND_HALF_UP), uncounted


def score_item(
    item: PushItem, window: Window, branch_id: str, days: Iterable[ItemDay]
) -> ItemScore:
    target = item.targets.get(branch_id, Decimal(0)).quantize(_PORTION)
    hole = hole_sentence(item.name, archived=item.archived, mapped=item.mapped)
    if hole is not None:
        return ItemScore(
            push_item_id=item.push_item_id,
            menu_item_id=item.menu_item_id,
            name=item.name,
            category=item.category,
            rate_per_portion=_fils(item.rate_per_portion),
            portion_target=target,
            portions=None,
            portions_above=Decimal(0),
            earned=Decimal("0.00"),
            hole=hole,
            no_qty_lines=0,
            words=hole,
        )
    portions, uncounted = _portions_for(item, window, branch_id, days)
    above = max(Decimal(0), portions - target)
    earned = _fils(above * item.rate_per_portion)
    return ItemScore(
        push_item_id=item.push_item_id,
        menu_item_id=item.menu_item_id,
        name=item.name,
        category=item.category,
        rate_per_portion=_fils(item.rate_per_portion),
        portion_target=target,
        portions=portions,
        portions_above=above,
        earned=earned,
        hole=None,
        no_qty_lines=uncounted,
        words=target_words(portions, target),
    )


def score_week(week: PushWeek, branch_id: str, days: Iterable[ItemDay]) -> WeekScore:
    items = tuple(score_item(item, week.window, branch_id, days) for item in week.items)
    earned = sum((item.earned for item in items), Decimal("0.00"))
    return WeekScore(
        push_week_id=week.push_week_id,
        window=week.window,
        items=items,
        earned=earned,
        empty=not items,
        words=NO_PUSH_LIST if not items else f"{len(items)} on the list",
    )


def split_pool(pool: Decimal, shares: Shares) -> Split:
    """pool × each share to the fil, the remainder to the sales share, so the
    three sum to the pool exactly (D2)."""
    manager = _fils(pool * shares.manager_pct / _HUNDRED)
    supervisor = _fils(pool * shares.supervisor_pct / _HUNDRED)
    sales = _fils(pool) - manager - supervisor
    return Split(shares=shares, manager=manager, supervisor=supervisor, sales=sales)


def compute_figures(
    scheme: SchemeMonth,
    branch_id: str,
    *,
    days: Sequence[LoadedDay],
    items: Sequence[ItemDay],
    currency: str,
) -> Figures:
    """One branch's figures for the scheme month from its loaded days (D8)."""
    targets = scheme.targets.get(branch_id)
    if targets is None:
        raise ValueError(f"branch {branch_id} has no targets in scheme month {scheme.month}")
    first, last = month_start(scheme.month), month_end(scheme.month)
    loaded = [d for d in days if d.branch_id == branch_id and first <= d.business_date <= last]
    days_loaded = len({d.business_date for d in loaded})
    net_sales = _fils(sum((d.net_sales for d in loaded), Decimal(0)))
    net_above = max(Decimal(0), net_sales - targets.net_sales_target)
    net_earned = _fils(net_above * targets.above_target_pct / _HUNDRED)

    weeks = tuple(score_week(week, branch_id, items) for week in scheme.weeks)
    items_earned = sum((week.earned for week in weeks), Decimal("0.00"))
    before_cap = _fils(items_earned + net_earned)
    cap = None if targets.cap is None else _fils(targets.cap)
    capped = cap is not None and before_cap > cap
    exact = cap if capped else before_cap
    if days_loaded == 0:
        pool: Decimal | None = None
        rounded: Decimal | None = None
        split: Split | None = None
        pool_words = NO_POOL_WORDS
    else:
        pool = exact
        rounded = _whole(exact)
        split = split_pool(exact, scheme.shares)
        pool_words = _money_words(exact, currency)
    return Figures(
        days_loaded=days_loaded,
        days_in_month=days_in_month(scheme.month),
        net_sales=net_sales,
        net_sales_target=_fils(targets.net_sales_target),
        net_above=_fils(net_above),
        above_target_pct=targets.above_target_pct.quantize(_PCT),
        net_earned=net_earned,
        weeks=weeks,
        items_earned=items_earned,
        pool_before_cap=before_cap,
        cap=cap,
        capped=capped,
        pool=pool,
        pool_rounded=rounded,
        split=split,
        net_words=f"{_money_words(net_sales, currency)} of "
        f"{_money_words(targets.net_sales_target, currency)}",
        pool_words=pool_words,
    )


def _notes(figures: Figures, currency: str) -> tuple[str, ...]:
    notes: list[str] = []
    for week in figures.weeks:
        if week.empty:
            notes.append(f"{week_words(week.window)}: {NO_PUSH_LIST}")
            continue
        for item in week.items:
            if item.hole is not None:
                notes.append(f"{week_words(week.window)}: {item.hole}")
            elif item.no_qty_lines:
                lines = "line" if item.no_qty_lines == 1 else "lines"
                notes.append(
                    f"{week_words(week.window)}: {item.no_qty_lines} till {lines} for "
                    f"{item.name} carried no quantity and are not counted"
                )
    if figures.capped and figures.cap is not None:
        notes.append(
            f"capped at {_money_words(figures.cap, currency)}; "
            f"{_money_words(figures.pool_before_cap, currency)} earned before the cap"
        )
    return tuple(notes)


def compose_statement(
    scheme: SchemeMonth,
    branch_id: str,
    *,
    days: Sequence[LoadedDay],
    items: Sequence[ItemDay],
    newest_loaded: datetime.date | None,
    approval: Approval | None,
    currency: str,
) -> Statement:
    """One branch's statement for one scheme month, derived on every read
    from the sales days and stored nowhere (D10, D11, D12).

    Provisional until every calendar day is loaded; final once approved, and
    then the figures are the approved snapshot - what was paid - with the
    live figures beside them and the note when the till now says otherwise.
    """
    live = compute_figures(scheme, branch_id, days=days, items=items, currency=currency)
    if approval is None:
        return Statement(
            branch_id=branch_id,
            month=month_start(scheme.month),
            newest_loaded=newest_loaded,
            status=PROVISIONAL,
            status_words=status_words(
                PROVISIONAL, live.days_loaded, live.days_in_month, differs=False
            ),
            figures=live,
            approval=None,
            till_now_says_otherwise=False,
            recomputed=None,
            notes=_notes(live, currency),
        )
    approved = figures_from_json(approval.figures)
    differs = figures_json(live) != approval.figures
    notes = list(_notes(approved, currency))
    if differs:
        notes.append(
            f"{TILL_NOW_SAYS_OTHERWISE}: a sales day was replaced after approval; the approved "
            f"figures stand and the recomputed ones are beside them"
        )
    return Statement(
        branch_id=branch_id,
        month=month_start(scheme.month),
        newest_loaded=newest_loaded,
        status=FINAL,
        status_words=status_words(
            FINAL, approved.days_loaded, approved.days_in_month, differs=differs
        ),
        figures=approved,
        approval=approval,
        till_now_says_otherwise=differs,
        recomputed=live if differs else None,
        notes=tuple(notes),
    )


def approvable(figures: Figures) -> str | None:
    """Why a statement cannot be approved, or None (D10): every calendar day
    of the month must be loaded for the branch."""
    if figures.days_loaded < figures.days_in_month:
        return (
            f"the month is provisional, {figures.days_loaded} of {figures.days_in_month} days "
            "loaded: load every day before approving"
        )
    return None


def week_in_view(scheme: SchemeMonth, day: datetime.date) -> PushWeek | None:
    """The push week that holds `day`, or None when the day is outside the
    month."""
    for week in scheme.weeks:
        if week.window.start <= day <= week.window.end:
            return week
    return None


def sentences(statement: Statement) -> list[str]:
    """Every composed sentence on a statement, for the banned-words test."""
    out = [statement.status_words, *statement.notes]
    for figures in (statement.figures, statement.recomputed):
        if figures is None:
            continue
        out += [figures.net_words, figures.pool_words]
        for week in figures.weeks:
            out.append(week.words)
            out += [item.words for item in week.items]
    return out


# --- the wire ---------------------------------------------------------------------


def _dec(value: Decimal | None) -> str | None:
    return None if value is None else str(value)


def _money(value) -> Decimal | None:
    return None if value is None else Decimal(value)


def _window_json(window: Window) -> dict:
    return {
        "start": window.start.isoformat(),
        "end": window.end.isoformat(),
        "words": week_words(window),
    }


def _window_from_json(data: dict) -> Window:
    return Window(
        datetime.date.fromisoformat(data["start"]), datetime.date.fromisoformat(data["end"])
    )


def shares_json(shares: Shares) -> dict:
    return {
        "manager_pct": str(shares.manager_pct.quantize(_PCT)),
        "supervisor_pct": str(shares.supervisor_pct.quantize(_PCT)),
        "sales_pct": str(shares.sales_pct.quantize(_PCT)),
    }


def shares_from_json(data: dict) -> Shares:
    return Shares(
        Decimal(data["manager_pct"]), Decimal(data["supervisor_pct"]), Decimal(data["sales_pct"])
    )


def _item_json(item: ItemScore) -> dict:
    return {
        "push_item_id": item.push_item_id,
        "menu_item_id": item.menu_item_id,
        "name": item.name,
        "category": item.category,
        "rate_per_portion": _dec(item.rate_per_portion),
        "portion_target": _dec(item.portion_target),
        "portions": _dec(item.portions),
        "portions_above": _dec(item.portions_above),
        "earned": _dec(item.earned),
        "hole": item.hole,
        "no_qty_lines": item.no_qty_lines,
        "words": item.words,
    }


def _item_from_json(data: dict) -> ItemScore:
    return ItemScore(
        push_item_id=data["push_item_id"],
        menu_item_id=data["menu_item_id"],
        name=data["name"],
        category=data["category"],
        rate_per_portion=Decimal(data["rate_per_portion"]),
        portion_target=Decimal(data["portion_target"]),
        portions=_money(data["portions"]),
        portions_above=Decimal(data["portions_above"]),
        earned=Decimal(data["earned"]),
        hole=data["hole"],
        no_qty_lines=int(data["no_qty_lines"]),
        words=data["words"],
    )


def _week_json(week: WeekScore) -> dict:
    return {
        "push_week_id": week.push_week_id,
        **_window_json(week.window),
        "items": [_item_json(item) for item in week.items],
        "earned": _dec(week.earned),
        "empty": week.empty,
        "words": week.words,
    }


def _week_from_json(data: dict) -> WeekScore:
    return WeekScore(
        push_week_id=data["push_week_id"],
        window=_window_from_json(data),
        items=tuple(_item_from_json(item) for item in data["items"]),
        earned=Decimal(data["earned"]),
        empty=bool(data["empty"]),
        words=data["words"],
    )


def _split_json(split: Split | None) -> dict | None:
    if split is None:
        return None
    return {
        "shares": shares_json(split.shares),
        "manager": _dec(split.manager),
        "supervisor": _dec(split.supervisor),
        "sales": _dec(split.sales),
    }


def _split_from_json(data: dict | None) -> Split | None:
    if data is None:
        return None
    return Split(
        shares=shares_from_json(data["shares"]),
        manager=Decimal(data["manager"]),
        supervisor=Decimal(data["supervisor"]),
        sales=Decimal(data["sales"]),
    )


def figures_json(figures: Figures) -> dict:
    """The figures on the wire and in an approval's snapshot: money as
    strings, never JSON numbers (C4)."""
    return {
        "days_loaded": figures.days_loaded,
        "days_in_month": figures.days_in_month,
        "net_sales": _dec(figures.net_sales),
        "net_sales_target": _dec(figures.net_sales_target),
        "net_above": _dec(figures.net_above),
        "above_target_pct": _dec(figures.above_target_pct),
        "net_earned": _dec(figures.net_earned),
        "weeks": [_week_json(week) for week in figures.weeks],
        "items_earned": _dec(figures.items_earned),
        "pool_before_cap": _dec(figures.pool_before_cap),
        "cap": _dec(figures.cap),
        "capped": figures.capped,
        "pool": _dec(figures.pool),
        "pool_rounded": _dec(figures.pool_rounded),
        "split": _split_json(figures.split),
        "net_words": figures.net_words,
        "pool_words": figures.pool_words,
    }


def figures_from_json(data: dict) -> Figures:
    """The snapshot back into figures, so an approved statement and a final
    card are drawn from what was approved, byte for byte."""
    return Figures(
        days_loaded=int(data["days_loaded"]),
        days_in_month=int(data["days_in_month"]),
        net_sales=Decimal(data["net_sales"]),
        net_sales_target=Decimal(data["net_sales_target"]),
        net_above=Decimal(data["net_above"]),
        above_target_pct=Decimal(data["above_target_pct"]),
        net_earned=Decimal(data["net_earned"]),
        weeks=tuple(_week_from_json(week) for week in data["weeks"]),
        items_earned=Decimal(data["items_earned"]),
        pool_before_cap=Decimal(data["pool_before_cap"]),
        cap=_money(data["cap"]),
        capped=bool(data["capped"]),
        pool=_money(data["pool"]),
        pool_rounded=_money(data["pool_rounded"]),
        split=_split_from_json(data["split"]),
        net_words=data["net_words"],
        pool_words=data["pool_words"],
    )


def approval_json(approval: Approval | None) -> dict | None:
    if approval is None:
        return None
    return {
        "approved_at": approval.approved_at.isoformat(),
        "actor": approval.actor,
        "reason": approval.reason,
    }


def statement_json(statement: Statement, *, branch_name: str) -> dict:
    return {
        "branch_id": statement.branch_id,
        "branch_name": branch_name,
        "month": month_key(statement.month),
        "newest_loaded": None
        if statement.newest_loaded is None
        else statement.newest_loaded.isoformat(),
        "status": statement.status,
        "status_words": statement.status_words,
        "figures": figures_json(statement.figures),
        "approval": approval_json(statement.approval),
        "till_now_says_otherwise": statement.till_now_says_otherwise,
        "recomputed": None if statement.recomputed is None else figures_json(statement.recomputed),
        "notes": list(statement.notes),
    }


def statement_from_json(data: dict) -> Statement:
    """A statement back off the wire - what the mock's fixtures and the
    scoreboard's tests are composed from."""
    approval = data.get("approval")
    return Statement(
        branch_id=data["branch_id"],
        month=parse_month_key(data["month"]),
        newest_loaded=None
        if data["newest_loaded"] is None
        else datetime.date.fromisoformat(data["newest_loaded"]),
        status=data["status"],
        status_words=data["status_words"],
        figures=figures_from_json(data["figures"]),
        approval=None
        if approval is None
        else Approval(
            approved_at=datetime.datetime.fromisoformat(approval["approved_at"]),
            actor=approval["actor"],
            reason=approval["reason"],
            figures=data["figures"],
        ),
        till_now_says_otherwise=bool(data["till_now_says_otherwise"]),
        recomputed=None if data["recomputed"] is None else figures_from_json(data["recomputed"]),
        notes=tuple(data["notes"]),
    )


def push_item_json(item: PushItem, *, kept_per_plate: Decimal | None, currency: str) -> dict:
    """A push item as the screen edits it: the rate, what the plate keeps
    beside it, the per-branch targets, and the hole sentence when the item
    can no longer be counted."""
    return {
        "id": item.push_item_id,
        "menu_item_id": item.menu_item_id,
        "name": item.name,
        "category": item.category,
        "rate_per_portion": _dec(_fils(item.rate_per_portion)),
        "kept_per_plate": _dec(kept_per_plate),
        "kept_words": kept_words(kept_per_plate, currency),
        "hole": hole_sentence(item.name, archived=item.archived, mapped=item.mapped),
        "targets": [
            {"branch_id": branch_id, "portion_target": _dec(target.quantize(_PORTION))}
            for branch_id, target in item.targets.items()
        ],
    }


def push_week_json(
    week: PushWeek,
    *,
    today: datetime.date,
    kept: Mapping[str, Decimal | None],
    currency: str,
) -> dict:
    """A push week as the screen shows it: its dates, whether it is frozen
    and why, and its list grouped by the menu's own category."""
    frozen = frozen_week_sentence(week.window, today)
    items = [
        push_item_json(item, kept_per_plate=kept.get(item.menu_item_id), currency=currency)
        for item in week.items
    ]
    return {
        "id": week.push_week_id,
        **_window_json(week.window),
        "frozen": frozen is not None,
        "frozen_words": frozen,
        "items": items,
        "categories": group_by_category(items),
    }


def scheme_month_json(
    scheme: SchemeMonth,
    *,
    created_at: datetime.datetime,
    today: datetime.date,
    kept: Mapping[str, Decimal | None],
    statements: Sequence[dict],
    currency: str,
) -> dict:
    """The scheme month block of `GET /api/incentive`: the month, the shares
    in force, each branch's targets, the weeks with their lists, and each
    branch's statement."""
    return {
        "id": scheme.scheme_month_id,
        "month": month_key(scheme.month),
        "words": month_words(scheme.month),
        "created_at": created_at.isoformat(),
        "shares": shares_json(scheme.shares),
        "targets": [
            {
                "branch_id": branch_id,
                "net_sales_target": _dec(_fils(target.net_sales_target)),
                "above_target_pct": _dec(target.above_target_pct.quantize(_PCT)),
                "cap": _dec(None if target.cap is None else _fils(target.cap)),
            }
            for branch_id, target in scheme.targets.items()
        ],
        "weeks": [
            push_week_json(week, today=today, kept=kept, currency=currency) for week in scheme.weeks
        ],
        "statements": list(statements),
    }


def menu_item_json(
    *,
    menu_item_id: str,
    name: str,
    category: str | None,
    kept_per_plate: Decimal | None,
    mapped: bool,
    currency: str,
) -> dict:
    """A live menu item as the push list picker offers it (D6, D7)."""
    return {
        "id": menu_item_id,
        "name": name,
        "category": category,
        "kept_per_plate": _dec(kept_per_plate),
        "kept_words": kept_words(kept_per_plate, currency),
        "mapped": mapped,
    }


def branch_json(
    *,
    branch_id: str,
    name: str,
    timezone: str,
    paused_at: datetime.datetime | None,
    previous_month_net_sales: Decimal | None,
    currency: str,
) -> dict:
    return {
        "id": branch_id,
        "name": name,
        "timezone": timezone,
        "paused_at": None if paused_at is None else paused_at.isoformat(),
        "previous_month_net_sales": _dec(
            None if previous_month_net_sales is None else _fils(previous_month_net_sales)
        ),
        "previous_month_words": previous_month_words(previous_month_net_sales, currency),
    }


def group_by_category(items: Sequence[dict]) -> list[dict]:
    """Menu items grouped by the menu's own category for the screen (D6):
    categories in alphabetical order, `Other` last for the items with none,
    the items in the order given. Each item dict is passed through untouched
    and read for its `category`."""
    groups: dict[str, list[dict]] = {}
    for item in items:
        groups.setdefault(item.get("category") or OTHER_CATEGORY, []).append(item)
    named = sorted(name for name in groups if name != OTHER_CATEGORY)
    if OTHER_CATEGORY in groups:
        named.append(OTHER_CATEGORY)
    return [
        {"category": name, "guidance": PUSH_GUIDANCE_WORDS, "items": groups[name]} for name in named
    ]
